services:
  www:
    build:
      context: .
      dockerfile: apps/v4/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_URL=
      - NEXT_PUBLIC_MAMDAS_DOCS=
    restart: unless-stopped
